version: "3.9"
services:
  web:
    build: .
    container_name: postrack
    ports:
      - "3001:3001"
    env_file:
      - ./.env   
    volumes:  
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped